// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzIR4k4TVepAdlwoihFVbeYl3Z_3gkSA',
    appId: '1:749584590064:web:2016d6ffea5a6bff02ce35',
    messagingSenderId: '749584590064',
    projectId: 'chat-app-3-1c701',
    authDomain: 'chat-app-3-1c701.firebaseapp.com',
    storageBucket: 'chat-app-3-1c701.appspot.com',
    measurementId: 'G-W62K6RWZS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHPWOHkFTf-oNOjfAEP0P4ZZ1gdZVmy4',
    appId: '1:749584590064:android:e2780cbc9489de1e02ce35',
    messagingSenderId: '749584590064',
    projectId: 'chat-app-3-1c701',
    storageBucket: 'chat-app-3-1c701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfwIJj0GYV0KQ9g3RDaYkEQpYToBAkUI',
    appId: '1:749584590064:ios:213fcc7a3e4eae9202ce35',
    messagingSenderId: '749584590064',
    projectId: 'chat-app-3-1c701',
    storageBucket: 'chat-app-3-1c701.appspot.com',
    iosBundleId: 'com.example.chatApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfwIJj0GYV0KQ9g3RDaYkEQpYToBAkUI',
    appId: '1:749584590064:ios:213fcc7a3e4eae9202ce35',
    messagingSenderId: '749584590064',
    projectId: 'chat-app-3-1c701',
    storageBucket: 'chat-app-3-1c701.appspot.com',
    iosBundleId: 'com.example.chatApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzIR4k4TVepAdlwoihFVbeYl3Z_3gkSA',
    appId: '1:749584590064:web:6179084016f17b4b02ce35',
    messagingSenderId: '749584590064',
    projectId: 'chat-app-3-1c701',
    authDomain: 'chat-app-3-1c701.firebaseapp.com',
    storageBucket: 'chat-app-3-1c701.appspot.com',
    measurementId: 'G-7STEDW3M2Y',
  );

}